---
- name: Test For Windows
  hosts: testwin
  gather_facts: false
  vars:
    uname: testbed
  remote_user: "{{uname}}"
  tasks:
    - name: ping win
      win_ping:
    - name: prepare ant
      win_chocolatey: name="ant -y"
      ignore_errors: True
    - name: set read-write
      script: ps_set.ps1
      ignore_errors: True
    - name: prepare jdk8
      win_chocolatey: name="jdk8 -y"
      ignore_errors: True
    - name: prepare cygwin
      win_chocolatey: name="cygwin -y"
      ignore_errors: True
    - name: prepare cyg-get
      win_chocolatey: name="cyg-get -y"
      ignore_errors: True
    - name: prepare python
      win_chocolatey: name="python2 -y"
      ignore_errors: True
    - name: prepare nodejs.install
      win_chocolatey: name="nodejs.install -y"
      ignore_errors: True
    - name: prepare ruby
      win_chocolatey: name="ruby -y" version="2.1.5"
      ignore_errors: True
    - name: prepare rubygems
      win_chocolatey: name="rubygems -y"
      ignore_errors: True
    - name: prepare ruby2.devkit
      win_chocolatey: name="ruby2.devkit -y"
      ignore_errors: True
    - name: prepare freeSSHD
      win_chocolatey: name="freeSSHD -y"
      ignore_errors: True
    - name: set tools by cyg-get
      script: ps_win.ps1
      ignore_errors: True
      

