---
- name: Test For Windows
  hosts: testwin
  gather_facts: false
  vars:
    uname: testbed
  remote_user: "{{uname}}"
  tasks:
    - name: ping win
      win_ping:
    - name: prepare ant
      win_chocolatey: name="ant -y"
    - name: prepare cygwin
      win_chocolatey: name="cygwin -y"
    - name: prepare cyg-get
      win_chocolatey: name="cyg-get -y"
    - name: prepare tools by cyg-get
      script: ps_win.ps1
        
        

