---
- name: Test For Windows
  hosts: testwin
  gather_facts: false
  vars:
    uname: testbed
  remote_user: "{{uname}}"
  tasks:
    - name: ping win
      win_ping:
    - name: prepare chocolatey
      win_chocolatey: name="chocolatey -y"
    - name: install win tools
      script: ps_win.ps1

